package:
  name: xfluo
  version: 0.1.1

extra:
  channels:
    - conda-forge

source:
  git_url: https://github.com/FabricioSMarin/xfluo.git
  git_tag: testing
  
build:
  noarch: python
  script: python setup.py install
  number: 0

python:
    version: 3.7

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy    
    - dxchange
    - scikit-image

test:
  # Python imports
  imports:
    - xfluo

about:
  home: http://xfluo.readthedocs.org
  license: BSD-3
  summary: 'Add docs to any xfluo.'
