package:
  name: xrftomo
  version: 0.1.1

extra:
  channels:
    - conda-forge

source:
  git_url: https://github.com/FabricioSMarin/xrftomo.git
  git_tag: testing
  
build:
  number: 0

python:
    version: 3.7

requirements:
  build:
    - python
    - setuptools
 
  run:
  - tomopy
  - pyqt
  - git
  - h5py
  - numpy
  - python=3.7
  - scikit-image
  - scipy
  - dxchange
  - pandas
  - seaborn
  - pyqtgraph
test:
  # Python imports
  imports:
    - xrftomo

about:
  home: http://xrftomo.readthedocs.org
  license: BSD-3
  summary: 'Add docs to any xrftomo.'
